### ISSUE TITLE
Refactor - improve driver API

### ISSUE THREAD

**Issue by golmek** [golemfactory/erc20_payment_lib#121]

**Comment by scx1332** [comment]
Reqc suggested some improvements in API

**Comment by scx1332** [comment]
Commits:
https://github.com/golemfactory/erc20_payment_lib/commit/288001df982afabba9188672b58d00ec16165ef6
https://github.com/golemfactory/erc20_payment_lib/commit/5d6bcad9ae31f2ede68e55b2200759b5dd7bbd1e
https://github.com/golemfactory/erc20_payment_lib/commit/61941c1c29f49c132f2637b53476749e9845776f
https://github.com/golemfactory/erc20_payment_lib/commit/d328b9db49011cd9ca9f28cba1952aafa27c71ee

Moved macros to common crate. Moved db ops to common crate. Cleanup db objects naming. Hide some public modules. Changes in async trait declarations.
