### ISSUE TITLE
Prepare Initial test scenarios

### ISSUE THREAD

**Issue by kamirr** [golemfactory/erc20_payment_lib#5]

**Comment by kamirr** [comment]
https://github.com/orgs/golemfactory/projects/50/views/3?pane=issue&itemId=34243938

**Comment by golmek** [comment]
@kamirr added Allowance oriented Test Scenarios for your verification and extension. Please look and let me know what You think.

cc: @nieznanysprawiciel Your input would be also much appreciated.

**Comment by golmek** [comment]
TODO: next task, extend initial test scenarios with details
