### ISSUE TITLE
Review payment API

### ISSUE THREAD

**Issue by kamirr** [golemfactory/erc20_payment_lib#6]
How new Payment Driver align with YAGNA. What information we would like to get in YAGNA payment module.

**Acceptance Criteria:**
- Review YAGNA API for interaction with Payment Driver
- Review Payment Driver API
- List of potential changes

**Comment by nieznanysprawiciel** [comment]
How does signing transactions works?
Previous driver calls identity api using GSB. In new driver I see that it must be initialized with private keys.
Not all identities will be unlocked on yagna start.

**Comment by golmek** [comment]
Recommendations:

- Update erc20_payment_lib : cleanup refactor
- New Method in erc20_payment_lib: status
- Create New Signer in Yagna (ERC20_NEXT) - for erc20_payment_lib to sign transaction in Yagna
- Logging status in Yagna

**Comment by golmek** [comment]
In Progress:

way of handling statuses:
- event per invoice ?
- global for payment driver
- how to propagate status to requestor agent - REST Endpoint?

**Comment by kamirr** [comment]
https://github.com/golemfactory/yagna/issues/2685
